__title__ = 'MindsDB OpenSearch handler'
__package_name__ = 'mindsdb_opensearch_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for OpenSearch"
__author__ = 'Kunal Bhattacharya'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2022- mindsdb'
